# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '8.x'
#   displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm install chromedriver --chromedriver-force-download
  displayName: 'npm install chromedriver'

- script: |
    node nightwatch.js tests/demo.js --config ./nightwatch.json
  displayName: 'nightwatch tests/demo.js'
  
# - script: |
#     node nightwatch.js tests/stepri.js --config ./nightwatch.json
#   displayName: 'nightwatch tests/stepri.js'

- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/tests_output/*.xml' 
    publishRunAttachments: true
