# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm install chromedriver --chromedriver-force-download
  displayName: 'npm install chromedriver'

# Use the --verbose flag for debugging 
- script: |
    node nightwatch.js tests/demo.js --config ./nightwatch.json
  displayName: 'nightwatch tests/demo.js'
  
- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'NUnit'
#     testResultsFiles: '**/tests_output/*.xml' 
    testResultsFiles: '**/tests_output/*' 
    publishRunAttachments: true
